spring.application.name=SocialApp
application.title=SocialApp
application.version=1.0.0

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/social-app
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework=error

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

